# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Thu May 10 21:36:57 2012
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(261, 551)
        MainWindow.setMinimumSize(QtCore.QSize(261, 551))
        MainWindow.setMaximumSize(QtCore.QSize(261, 551))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 261, 531))
        self.tabWidget.setMinimumSize(QtCore.QSize(261, 441))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.but_genSpline = QtGui.QPushButton(self.tab)
        self.but_genSpline.setGeometry(QtCore.QRect(80, 470, 99, 24))
        self.but_genSpline.setCheckable(False)
        self.but_genSpline.setAutoDefault(False)
        self.but_genSpline.setDefault(False)
        self.but_genSpline.setObjectName(_fromUtf8("but_genSpline"))
        self.contour_resolution = QtGui.QSpinBox(self.tab)
        self.contour_resolution.setGeometry(QtCore.QRect(140, 440, 91, 23))
        self.contour_resolution.setMaximum(10000)
        self.contour_resolution.setSingleStep(100)
        self.contour_resolution.setProperty(_fromUtf8("value"), 2000)
        self.contour_resolution.setObjectName(_fromUtf8("contour_resolution"))
        self.tab_inpoints = QtGui.QTableWidget(self.tab)
        self.tab_inpoints.setGeometry(QtCore.QRect(0, 120, 251, 291))
        self.tab_inpoints.setRowCount(10)
        self.tab_inpoints.setObjectName(_fromUtf8("tab_inpoints"))
        self.tab_inpoints.setColumnCount(2)
        self.tab_inpoints.setRowCount(10)
        item = QtGui.QTableWidgetItem()
        self.tab_inpoints.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tab_inpoints.setHorizontalHeaderItem(1, item)
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 440, 130, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.spin_rows = QtGui.QSpinBox(self.tab)
        self.spin_rows.setGeometry(QtCore.QRect(100, 90, 56, 23))
        self.spin_rows.setObjectName(_fromUtf8("spin_rows"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(60, 90, 40, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.radioImportSVG = QtGui.QRadioButton(self.tab)
        self.radioImportSVG.setGeometry(QtCore.QRect(10, 10, 231, 17))
        self.radioImportSVG.setChecked(True)
        self.radioImportSVG.setAutoExclusive(True)
        self.radioImportSVG.setObjectName(_fromUtf8("radioImportSVG"))
        self.radioManualInput = QtGui.QRadioButton(self.tab)
        self.radioManualInput.setGeometry(QtCore.QRect(10, 60, 231, 17))
        self.radioManualInput.setObjectName(_fromUtf8("radioManualInput"))
        self.line = QtGui.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(10, 420, 231, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.butBrowseSVG = QtGui.QPushButton(self.tab)
        self.butBrowseSVG.setGeometry(QtCore.QRect(184, 30, 61, 23))
        self.butBrowseSVG.setObjectName(_fromUtf8("butBrowseSVG"))
        self.lineSelectedSVG = QtGui.QLineEdit(self.tab)
        self.lineSelectedSVG.setEnabled(True)
        self.lineSelectedSVG.setGeometry(QtCore.QRect(10, 32, 171, 20))
        self.lineSelectedSVG.setReadOnly(True)
        self.lineSelectedSVG.setObjectName(_fromUtf8("lineSelectedSVG"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(60, 250, 80, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(62, 280, 80, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.Xresolution = QtGui.QSpinBox(self.tab_2)
        self.Xresolution.setGeometry(QtCore.QRect(140, 249, 91, 23))
        self.Xresolution.setMaximum(3000)
        self.Xresolution.setSingleStep(100)
        self.Xresolution.setProperty(_fromUtf8("value"), 1000)
        self.Xresolution.setObjectName(_fromUtf8("Xresolution"))
        self.Yresolution = QtGui.QSpinBox(self.tab_2)
        self.Yresolution.setGeometry(QtCore.QRect(140, 279, 91, 23))
        self.Yresolution.setMaximum(3000)
        self.Yresolution.setSingleStep(100)
        self.Yresolution.setProperty(_fromUtf8("value"), 1000)
        self.Yresolution.setObjectName(_fromUtf8("Yresolution"))
        self.but_genSurf = QtGui.QPushButton(self.tab_2)
        self.but_genSurf.setGeometry(QtCore.QRect(80, 320, 99, 24))
        self.but_genSurf.setCheckable(False)
        self.but_genSurf.setAutoDefault(False)
        self.but_genSurf.setDefault(False)
        self.but_genSurf.setObjectName(_fromUtf8("but_genSurf"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(21, 21, 120, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.spin_thickness = QtGui.QDoubleSpinBox(self.tab_2)
        self.spin_thickness.setGeometry(QtCore.QRect(140, 20, 90, 23))
        self.spin_thickness.setDecimals(2)
        self.spin_thickness.setSingleStep(0.1)
        self.spin_thickness.setProperty(_fromUtf8("value"), 1.0)
        self.spin_thickness.setObjectName(_fromUtf8("spin_thickness"))
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(40, 51, 100, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.spin_layer = QtGui.QDoubleSpinBox(self.tab_2)
        self.spin_layer.setGeometry(QtCore.QRect(140, 50, 90, 23))
        self.spin_layer.setDecimals(2)
        self.spin_layer.setSingleStep(0.1)
        self.spin_layer.setProperty(_fromUtf8("value"), 0.1)
        self.spin_layer.setObjectName(_fromUtf8("spin_layer"))
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(20, 350, 221, 71))
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.line_2 = QtGui.QFrame(self.tab_2)
        self.line_2.setGeometry(QtCore.QRect(17, 230, 211, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(40, 151, 100, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.spin_exponConstant = QtGui.QDoubleSpinBox(self.tab_2)
        self.spin_exponConstant.setGeometry(QtCore.QRect(140, 150, 90, 23))
        self.spin_exponConstant.setDecimals(2)
        self.spin_exponConstant.setMinimum(0.01)
        self.spin_exponConstant.setMaximum(1000.0)
        self.spin_exponConstant.setSingleStep(1.0)
        self.spin_exponConstant.setProperty(_fromUtf8("value"), 5.0)
        self.spin_exponConstant.setObjectName(_fromUtf8("spin_exponConstant"))
        self.exponentialThicknessRadio = QtGui.QRadioButton(self.tab_2)
        self.exponentialThicknessRadio.setGeometry(QtCore.QRect(10, 130, 241, 21))
        self.exponentialThicknessRadio.setChecked(True)
        self.exponentialThicknessRadio.setObjectName(_fromUtf8("exponentialThicknessRadio"))
        self.percentualThicknessRadio = QtGui.QRadioButton(self.tab_2)
        self.percentualThicknessRadio.setGeometry(QtCore.QRect(10, 180, 231, 21))
        self.percentualThicknessRadio.setObjectName(_fromUtf8("percentualThicknessRadio"))
        self.quadraticThicknessRadio = QtGui.QRadioButton(self.tab_2)
        self.quadraticThicknessRadio.setGeometry(QtCore.QRect(10, 100, 231, 21))
        self.quadraticThicknessRadio.setObjectName(_fromUtf8("quadraticThicknessRadio"))
        self.spin_percentualConstant = QtGui.QDoubleSpinBox(self.tab_2)
        self.spin_percentualConstant.setGeometry(QtCore.QRect(140, 199, 90, 23))
        self.spin_percentualConstant.setDecimals(0)
        self.spin_percentualConstant.setMinimum(0.0)
        self.spin_percentualConstant.setMaximum(100.0)
        self.spin_percentualConstant.setSingleStep(1.0)
        self.spin_percentualConstant.setProperty(_fromUtf8("value"), 10.0)
        self.spin_percentualConstant.setObjectName(_fromUtf8("spin_percentualConstant"))
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(40, 200, 100, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionContour = QtGui.QAction(MainWindow)
        self.actionContour.setObjectName(_fromUtf8("actionContour"))
        self.actionSurface = QtGui.QAction(MainWindow)
        self.actionSurface.setObjectName(_fromUtf8("actionSurface"))
        self.actionOpenFile = QtGui.QAction(MainWindow)
        self.actionOpenFile.setObjectName(_fromUtf8("actionOpenFile"))
        self.actionSaveAs = QtGui.QAction(MainWindow)
        self.actionSaveAs.setObjectName(_fromUtf8("actionSaveAs"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "finFoil", None, QtGui.QApplication.UnicodeUTF8))
        self.but_genSpline.setText(QtGui.QApplication.translate("MainWindow", "Generate", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_inpoints.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_inpoints.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Contour resolution:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Rows:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioImportSVG.setText(QtGui.QApplication.translate("MainWindow", "Import SVG", None, QtGui.QApplication.UnicodeUTF8))
        self.radioManualInput.setText(QtGui.QApplication.translate("MainWindow", "Manual input", None, QtGui.QApplication.UnicodeUTF8))
        self.butBrowseSVG.setText(QtGui.QApplication.translate("MainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Contour", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "X resolution:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Y resolution:", None, QtGui.QApplication.UnicodeUTF8))
        self.but_genSurf.setText(QtGui.QApplication.translate("MainWindow", "Generate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Fin base thickness:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Layer thickness:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Generate a contour before generating a surface.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Profile constant:", None, QtGui.QApplication.UnicodeUTF8))
        self.exponentialThicknessRadio.setText(QtGui.QApplication.translate("MainWindow", "Use exponential thickness profile", None, QtGui.QApplication.UnicodeUTF8))
        self.percentualThicknessRadio.setText(QtGui.QApplication.translate("MainWindow", "Use percentual thickness profile", None, QtGui.QApplication.UnicodeUTF8))
        self.quadraticThicknessRadio.setText(QtGui.QApplication.translate("MainWindow", "Use Quadratic thickness profile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Percentage:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Surface", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionContour.setText(QtGui.QApplication.translate("MainWindow", "Contour", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSurface.setText(QtGui.QApplication.translate("MainWindow", "Surface", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenFile.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))

